name: Pipelines Credentials
description: Fetch Pipelines Credentials
inputs:
  PIPELINES_TOKEN_PATH:
    required: true
  FALLBACK_TOKEN:
    required: true
  api_base_url:
    default: "https://api.prod.app.gruntwork.io/api/v1"
outputs:
  PIPELINES_TOKEN:
    value: ${{ steps.get_token.outputs.PIPELINES_TOKEN }}

runs:
  using: composite
  steps:
    - name: Fetch Pipelines Token
      id: get_token
      uses: actions/github-script@v7
      env:
        FALLBACK_TOKEN: ${{ inputs.FALLBACK_TOKEN }}
        PIPELINES_TOKEN_PATH: ${{ inputs.PIPELINES_TOKEN_PATH }}
        API_BASE_URL: ${{ inputs.api_base_url }}
      with:
        script: |
          const sleep = (ms) => new Promise(r => setTimeout(r, ms))

          const isRetryableError = (error) => {
            const msg = String(error)
            // Network errors
            if (/TypeError|ECONN|ETIMEDOUT|ENOTFOUND|EAI_AGAIN/.test(msg)) return true
            // HTTP 5xx or 429 (rate limit)
            const statusMatch = msg.match(/: (\d{3})$/)
            if (statusMatch) {
              const status = parseInt(statusMatch[1])
              return status >= 500 || status === 429
            }
            return false
          }

          const withRetry = async (fn, retries = 3) => {
            for (let i = 1; i <= retries; i++) {
              try {
                return await fn()
              } catch (error) {
                console.log(`Attempt ${i}/${retries} failed: ${error}`)
                if (i < retries && isRetryableError(error)) {
                  await sleep(1000 * i + Math.random() * 2000)
                } else {
                  throw error
                }
              }
            }
          }

          try {
            const apiBaseURL = process.env.API_BASE_URL

            const idToken = await withRetry(() =>
              core.getIDToken("https://api.prod.app.gruntwork.io")
            )

            const providerToken = await withRetry(async () => {
              const res = await fetch(`${apiBaseURL}/tokens/auth/login`, {
                method: "POST",
                headers: { "Authorization": `Bearer ${idToken}` }
              })
              if (!res.ok) throw new Error(`Login failed: ${res.status}`)
              return (await res.json()).token
            })

            const token = await withRetry(async () => {
              const res = await fetch(`${apiBaseURL}/tokens/pat/${process.env.PIPELINES_TOKEN_PATH}`, {
                headers: { "Authorization": `Bearer ${providerToken}` }
              })
              if (!res.ok) throw new Error(`Token fetch failed: ${res.status}`)
              return (await res.json()).token
            })

            console.log("Setting PIPELINES_TOKEN to GitHubApp token")
            core.setOutput('PIPELINES_TOKEN', token)
            return
          } catch (error) {
            console.log(`Failed to get pipelines token: ${error}`)
          }

          if (!process.env.FALLBACK_TOKEN) {
            core.setFailed("Unable to fetch credentials via Gruntwork.io GitHub App and no FALLBACK_TOKEN provided.")
            return
          }

          console.log("Setting PIPELINES_TOKEN to fallback token")
          core.setOutput('PIPELINES_TOKEN', process.env.FALLBACK_TOKEN.trim())

